#pragma once

#include <Arduino.h>
#include "webconfig.h"
#include "user_config.h"

// name for the wifi config file
#define CONFFILENAMEWIFI "/wifi.conf"

String paramsWifi = "["
                "{"
                "'name':'ssid1',"
                "'label':'WiFI name 1',"
                "'type':" + String(INPUTTEXT) + ","
                "'default':'" + String(STA_SSID1) + "'"
                "},"
                "{"
                "'name':'pwd1',"
                "'label':'WiFi password 1',"
                "'type':" + String(INPUTPASSWORD) + ","
                "'default':'" + String(STA_PASS1) + "'"
                "},"
                "{"
                "'name':'ssid2',"
                "'label':'WiFI name 2',"
                "'type':" + String(INPUTTEXT) + ","
                "'default':'" + String(STA_SSID2) + "'"
                "},"
                "{"
                "'name':'pwd2',"
                "'label':'WiFi password 2',"
                "'type':" + String(INPUTPASSWORD) + ","
                "'default':'" + String(STA_PASS2) + "'"
                "},"
                "{"
                "'name':'hostname',"
                "'label':'Hostname',"
                "'type':" + String(INPUTTEXT) + ","
                "'default':'" + String(APP_HOSTNAME) + "'"
                "}"
                "]";
